---
title: "DATA609_HW_HWK4"
author: "Dan Fanelli"
date: "9/27/2016"
output: html_document
---

```{r}
heights <- c(60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80)
weights <- c(132,136,141,145,150,155,160,165,170,175,180,185,190,195,201,206,212,218,223,229,234)

df <- data.frame(heights = heights, weights = weights)
fit <- lm(weights ~ heights, data = df)

output.df <- data.frame(heights = df$heights)

SST <- sum((weights - mean(weights))^2)
SSR <- sum((predict(fit) - mean(weights))^2)
SSE <- SST - SSR # SSE <- sum(resid(softdrink.lm)^2)
R2 <- summary(fit)$r.squared

SSE
SSR
SST
R2

plot(density(resid(fit))) #A density plot
qqnorm(resid(fit)) # A quantile normal plot - good for checking normality
qqline(resid(fit))

```

Predict as function of height cubed

```{r}
heights <- c(60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80)
weights <- c(132,136,141,145,150,155,160,165,170,175,180,185,190,195,201,206,212,218,223,229,234)

df <- data.frame(heights = heights, weights = weights)
fit <- lm(weights ~ heights^3, data = df)

output.df <- data.frame(heights = df$heights)

SST <- sum((weights - mean(weights))^2)
SSR <- sum((predict(fit) - mean(weights))^2)
SSE <- SST - SSR # SSE <- sum(resid(softdrink.lm)^2)
R2 <- summary(fit)$r.squared

SSE
SSR
SST
R2

plot(density(resid(fit))) #A density plot
qqnorm(resid(fit)) # A quantile normal plot - good for checking normality
qqline(resid(fit))

```

